export const sample_seeds = [
    {
        id: '1',
        name: 'Sunflower',
        price: 2,
        sow: ['May', 'June', 'July'],
        position: 'direct sun',
        inout: 'outdoor',
        germination: '7-10',
        colour: ['yellow'],
        type: 'flower',
        height: 1.5,
        stars: 4,
        tags: ['yellow', 'large', 'giant'],
        imageUrl: 'sunflower.png',
        favourite: 'yes'
    },
    {
        id: '2',
        name: 'Pea',
        price: 1.5,
        sow: ['April', 'May'],
        position: 'direct sun',
        inout: 'outdoor',
        germination: '7-10',
        colour: ['green'],
        type: ['vegetable'],
        height: 1.8,
        stars: 2,
        tags: ['legume'],
        imageUrl: 'pea.png',
        favourite: 'yes'
    },
    {
        id: '3',
        name: 'carrot',
        price: 1,
        sow: ['February', 'March', 'April'],
        position: 'direct sun',
        inout: 'outdoor',
        germination: '7-10',
        colour: ['orange','green'],
        type: ['vegetable'],
        height: 0.2,
        stars: 3.5,
        tags: ['root'],
        imageUrl: 'carrot.png',
        favourite: 'no'
    },
    {
        id: '4',
        name: 'strawberry',
        price: 1,
        sow: ['March', 'April'],
        position: 'direct sun',
        inout: 'outdoor',
        germination: '7-10',
        colour: ['red','green'],
        type: ['fruit'],
        height: 0.2,
        stars: 3.5,
        tags: ['root'],
        imageUrl: 'strawberry.png',
        favourite: 'yes'
    },
    {
        id: '5',
        name: 'broccoli',
        price: 1,
        sow: ['January', 'February', 'March'],
        position: 'direct sun',
        inout: 'outdoor',
        germination: '7-10',
        colour: ['red','green'],
        type: ['fruit'],
        height: 0.2,
        stars: 3.5,
        tags: ['root'],
        imageUrl: 'broccoli.png',
        favourite: 'no'
    },
];