export const sample_seeds = [
    {
        id: '1',
        name: 'Sunflower',
        price: 2,
        sow: ['May', 'Jun', 'Jul'],
        position: 'direct sun',
        inout: 'outdoor',
        germination: '7-10',
        colour: ['yellow'],
        type: 'flower',
        height: 1.5,
        stars: 4,
        tags: ['yellow', 'large', 'giant'],
        imageUrl: 'sunflower.png',
        favourite: true
    },
    {
        id: '2',
        name: 'Pea',
        price: 1.5,
        sow: ['Apr', 'May'],
        position: 'direct sun',
        inout: 'outdoor',
        germination: '7-10',
        colour: ['green'],
        type: ['vegetable'],
        height: 1.8,
        stars: 2,
        tags: ['legume'],
        imageUrl: 'pea.png',
        favourite: true
    },
    {
        id: '3',
        name: 'carrot',
        price: 1,
        sow: ['Feb', 'Mar', 'Apr'],
        position: 'direct sun',
        inout: 'outdoor',
        germination: '7-10',
        colour: ['orange','green'],
        type: ['vegetable'],
        height: 0.2,
        stars: 5,
        tags: ['root'],
        imageUrl: 'carrot.png',
        favourite: false
    },
    {
        id: '4',
        name: 'strawberry',
        price: 1,
        sow: ['Mar', 'Apr'],
        position: 'direct sun',
        inout: 'outdoor',
        germination: '7-10',
        colour: ['red','green'],
        type: ['fruit'],
        height: 0.2,
        stars: 2.5,
        tags: ['root'],
        imageUrl: 'strawberry.png',
        favourite: false
    },
    {
        id: '5',
        name: 'broccoli',
        price: 1,
        sow: ['Jan', 'Feb', 'Mar'],
        position: 'direct sun',
        inout: 'outdoor',
        germination: '7-10',
        colour: ['red','green'],
        type: ['fruit'],
        height: 0.2,
        stars: 3.5,
        tags: ['root'],
        imageUrl: 'broccoli.png',
        favourite: true
    },
];